# Generated by Django 3.2.18 on 2023-04-07 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('ground_editsql', models.CharField(max_length=256)),
                ('pred_editsql', models.CharField(max_length=256)),
                ('ground_sql', models.CharField(blank=True, max_length=256, null=True)),
                ('pred_sql', models.CharField(blank=True, max_length=256, null=True)),
                ('hardness', models.CharField(max_length=9)),
                ('components', models.TextField()),
                ('comp_explanations', models.TextField()),
                ('confidence', models.FloatField()),
                ('comp_confidence', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spider_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=100)),
                ('db_schema', models.TextField()),
                ('db_values', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_response', models.BooleanField(blank=True, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.samples')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='samples',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.spider_db'),
        ),
    ]
