# Generated by Django 3.2.18 on 2023-04-08 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='feature_attribution',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
