# Generated by Django 3.2.18 on 2023-04-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_samples_correct_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='db_records',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samples',
            name='correct_prediction',
            field=models.BooleanField(),
        ),
    ]
