# Generated by Django 3.2.18 on 2023-04-11 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_db_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='database_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
