# Generated by Django 3.2.18 on 2023-04-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_samples_database_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samples',
            name='database',
        ),
    ]
