# Generated by Django 3.2.18 on 2023-04-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_samples_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hyperparameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_samples_per_user', models.IntegerField()),
            ],
        ),
    ]
