# Generated by Django 4.2.4 on 2023-08-24 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_hyperparameters"),
    ]

    operations = [
        migrations.CreateModel(
            name="SqlExplanation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample", models.CharField(max_length=100)),
                ("step", models.IntegerField()),
                ("explanation", models.TextField()),
                ("feature_attribution", models.TextField()),
                ("confidence", models.FloatField()),
                ("database_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="samples",
            name="sample_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
