# Generated by Django 4.2.4 on 2023-08-24 01:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_sqlexplanation_samples_sample_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="samples",
            name="comp_confidence",
        ),
        migrations.RemoveField(
            model_name="samples",
            name="comp_explanations",
        ),
        migrations.RemoveField(
            model_name="samples",
            name="ground_editsql",
        ),
        migrations.RemoveField(
            model_name="samples",
            name="pred_editsql",
        ),
    ]
