# Generated by Django 4.2.4 on 2023-08-24 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_remove_samples_comp_confidence_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="samples",
            name="components",
        ),
    ]
