# Generated by Django 4.2.4 on 2023-08-24 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_remove_samples_components"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spider_db",
            old_name="db_schema",
            new_name="column_names",
        ),
        migrations.AddField(
            model_name="spider_db",
            name="table_names",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
