# Generated by Django 4.2.4 on 2023-08-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_spider_db_all_dbs"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
