# Generated by Django 4.2.4 on 2023-08-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_study_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="created",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="study",
            name="updated",
            field=models.DateTimeField(),
        ),
    ]
