# Generated by Django 4.2.4 on 2023-08-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_usertransaprency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertransaprency",
            name="user_id",
        ),
        migrations.AddField(
            model_name="usertransaprency",
            name="username",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
