# Generated by Django 4.2.4 on 2023-08-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_remove_usertransaprency_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertransaprency",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
