# Generated by Django 4.2.4 on 2023-08-31 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_alter_usertransaprency_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertransaprency",
            name="UserTransaprency",
        ),
    ]
