# Generated by Django 4.2.4 on 2023-08-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_remove_usertransaprency_usertransaprency"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertransaprency",
            name="user_transparency",
            field=models.CharField(default="Low", max_length=100),
        ),
    ]
