# Generated by Django 4.2.4 on 2023-09-19 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_study_is_training_sample"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="study",
            name="is_training_sample",
        ),
    ]
