# Generated by Django 4.2.4 on 2023-09-19 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0022_remove_study_is_training_sample"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingSamples",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_name", models.CharField(max_length=100)),
                ("question", models.CharField(max_length=256)),
                ("ground_sql", models.CharField(blank=True, max_length=256, null=True)),
                ("pred_sql", models.CharField(blank=True, max_length=256, null=True)),
                ("hardness", models.CharField(max_length=9)),
                ("db_records", models.TextField(blank=True, null=True)),
                ("feature_attribution", models.TextField()),
                ("confidence", models.FloatField()),
                ("correct_prediction", models.BooleanField()),
                ("database_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TrainingStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_response", models.BooleanField(blank=True, null=True)),
                ("viewed", models.BooleanField(default=False)),
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField()),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.samples"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
