# Generated by Django 4.2.4 on 2023-10-07 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0026_usertrust"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usertrust",
            old_name="usert_trust_status",
            new_name="user_trust_status",
        ),
    ]
