# Generated by Django 4.2.4 on 2023-10-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0027_rename_usert_trust_status_usertrust_user_trust_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="hyperparameters",
            name="agreement_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
