# Generated by Django 4.2.4 on 2023-10-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0030_remove_usertrust_user_trust_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jiantrustscale",
            name="initial_survey",
            field=models.BooleanField(default=True),
        ),
    ]
