# Generated by Django 4.2.4 on 2023-10-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0031_jiantrustscale_initial_survey"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usertrust",
            old_name="trust_unitl_no_reason",
            new_name="like_machine_to_assist",
        ),
        migrations.AddField(
            model_name="usertrust",
            name="trust_until_no_reason",
            field=models.IntegerField(
                choices=[(0, "Low"), (1, "Mid"), (2, "High")], default=0
            ),
        ),
    ]
