# Generated by Django 4.2.4 on 2023-11-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "main",
            "0032_rename_trust_unitl_no_reason_usertrust_like_machine_to_assist_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertrust",
            name="like_machine_to_assist",
        ),
        migrations.AddField(
            model_name="jiantrustscale",
            name="system_action_harmful",
            field=models.IntegerField(
                choices=[
                    (1, "one"),
                    (2, "two"),
                    (3, "three"),
                    (4, "four"),
                    (5, "five"),
                    (6, "six"),
                    (7, "seven"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="jiantrustscale",
            name="system_confident",
            field=models.IntegerField(
                choices=[
                    (1, "one"),
                    (2, "two"),
                    (3, "three"),
                    (4, "four"),
                    (5, "five"),
                    (6, "six"),
                    (7, "seven"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="jiantrustscale",
            name="system_dependable",
            field=models.IntegerField(
                choices=[
                    (1, "one"),
                    (2, "two"),
                    (3, "three"),
                    (4, "four"),
                    (5, "five"),
                    (6, "six"),
                    (7, "seven"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="jiantrustscale",
            name="system_familiar",
            field=models.IntegerField(
                choices=[
                    (1, "one"),
                    (2, "two"),
                    (3, "three"),
                    (4, "four"),
                    (5, "five"),
                    (6, "six"),
                    (7, "seven"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="jiantrustscale",
            name="system_integrity",
            field=models.IntegerField(
                choices=[
                    (1, "one"),
                    (2, "two"),
                    (3, "three"),
                    (4, "four"),
                    (5, "five"),
                    (6, "six"),
                    (7, "seven"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="jiantrustscale",
            name="system_reliable",
            field=models.IntegerField(
                choices=[
                    (1, "one"),
                    (2, "two"),
                    (3, "three"),
                    (4, "four"),
                    (5, "five"),
                    (6, "six"),
                    (7, "seven"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="jiantrustscale",
            name="system_security",
            field=models.IntegerField(
                choices=[
                    (1, "one"),
                    (2, "two"),
                    (3, "three"),
                    (4, "four"),
                    (5, "five"),
                    (6, "six"),
                    (7, "seven"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="jiantrustscale",
            name="system_wary_system",
            field=models.IntegerField(
                choices=[
                    (1, "one"),
                    (2, "two"),
                    (3, "three"),
                    (4, "four"),
                    (5, "five"),
                    (6, "six"),
                    (7, "seven"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="jiantrustscale",
            name="systen_trust",
            field=models.IntegerField(
                choices=[
                    (1, "one"),
                    (2, "two"),
                    (3, "three"),
                    (4, "four"),
                    (5, "five"),
                    (6, "six"),
                    (7, "seven"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="usertrust",
            name="easy_for_me_to_trust",
            field=models.IntegerField(
                choices=[
                    (1, "Strongly disagree"),
                    (2, "Somewhat disagree"),
                    (3, "Neither agree or disagree"),
                    (4, "Somewhat agree"),
                    (5, "Strongly agree"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="usertrust",
            name="likely_to_trust",
            field=models.IntegerField(
                choices=[
                    (1, "Strongly disagree"),
                    (2, "Somewhat disagree"),
                    (3, "Neither agree or disagree"),
                    (4, "Somewhat agree"),
                    (5, "Strongly agree"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="usertrust",
            name="rely_on_machine_assist",
            field=models.IntegerField(
                choices=[
                    (1, "Strongly disagree"),
                    (2, "Somewhat disagree"),
                    (3, "Neither agree or disagree"),
                    (4, "Somewhat agree"),
                    (5, "Strongly agree"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="jiantrustscale",
            name="system_sus_intent",
            field=models.IntegerField(
                choices=[
                    (1, "one"),
                    (2, "two"),
                    (3, "three"),
                    (4, "four"),
                    (5, "five"),
                    (6, "six"),
                    (7, "seven"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="jiantrustscale",
            name="system_underhanded",
            field=models.IntegerField(
                choices=[
                    (1, "one"),
                    (2, "two"),
                    (3, "three"),
                    (4, "four"),
                    (5, "five"),
                    (6, "six"),
                    (7, "seven"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="jiantrustscale",
            name="sytem_deceptive",
            field=models.IntegerField(
                choices=[
                    (1, "one"),
                    (2, "two"),
                    (3, "three"),
                    (4, "four"),
                    (5, "five"),
                    (6, "six"),
                    (7, "seven"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="usertrust",
            name="most_part_i_distrust",
            field=models.IntegerField(
                choices=[
                    (1, "Strongly disagree"),
                    (2, "Somewhat disagree"),
                    (3, "Neither agree or disagree"),
                    (4, "Somewhat agree"),
                    (5, "Strongly agree"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="usertrust",
            name="tendency_to_trust",
            field=models.IntegerField(
                choices=[
                    (1, "Strongly disagree"),
                    (2, "Somewhat disagree"),
                    (3, "Neither agree or disagree"),
                    (4, "Somewhat agree"),
                    (5, "Strongly agree"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="usertrust",
            name="trust_until_no_reason",
            field=models.IntegerField(
                choices=[
                    (1, "Strongly disagree"),
                    (2, "Somewhat disagree"),
                    (3, "Neither agree or disagree"),
                    (4, "Somewhat agree"),
                    (5, "Strongly agree"),
                ],
                default=3,
            ),
        ),
    ]
