# Generated by Django 4.2.4 on 2023-11-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0033_remove_usertrust_like_machine_to_assist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertrust",
            name="user_trust_status",
            field=models.BooleanField(default=False),
        ),
    ]
