# Generated by Django 4.2.4 on 2023-12-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0034_usertrust_user_trust_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingstudy",
            name="before_study",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usertrust",
            name="before_study",
            field=models.BooleanField(default=True),
        ),
    ]
