# Generated by Django 4.2.4 on 2023-12-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0035_trainingstudy_before_study_usertrust_before_study"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingstudy",
            name="before_study",
        ),
        migrations.AddField(
            model_name="jiantrustscale",
            name="before_study",
            field=models.BooleanField(default=True),
        ),
    ]
