# Generated by Django 4.2.4 on 2023-12-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0036_remove_trainingstudy_before_study_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdemographic",
            name="race",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
