# Generated by Django 4.2.4 on 2023-12-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0037_userdemographic_race"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdemographic",
            name="gender",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
