# Generated by Django 4.2.4 on 2024-01-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0039_usertrainingmeta"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertrainingmeta",
            name="general_task",
            field=models.BooleanField(default=False),
        ),
    ]
