# Generated by Django 4.2.4 on 2024-01-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0041_usertrainingmeta_begin_train"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertrainingmeta",
            name="begin_study",
            field=models.BooleanField(default=False),
        ),
    ]
